default: &default
  adapter: postgresql
  encoding: unicode
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  host: localhost
  port: 5432
  username: <%= Rails.application.credentials.postgres[:username] %>
  password: <%= Rails.application.credentials.postgres[:password] %>

development:
  <<: *default
  database: Pagespeed_development

test:
  <<: *default
  database: Pagespeed_test

production:
  <<: *default
  database: Pagespeed_production